# Generated by Django 3.2.12 on 2022-02-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='booked_by',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='table_id',
            new_name='booked_table',
        ),
    ]
