# Generated by Django 3.2.12 on 2022-02-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220218_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_table',
            old_name='steats',
            new_name='seats',
        ),
    ]
