# Generated by Django 3.2.12 on 2022-02-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_steats_dinner_table_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Dinner_table',
            new_name='DinnerTable',
        ),
    ]
