# Generated by Django 3.2.12 on 2022-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220220_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_table',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_table',
            field=models.ManyToManyField(to='api.DinnerTable'),
        ),
    ]
